# -*- coding: utf-8 -*-
"""코딩도장 1-7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PkEFxHOks2uKyr5gXTkIBdadblcAPwpp

#unit 3 시작
"""

print("Hello, World!")

# 연습문제
print('Hello, world!')
print("Python Programming")

"""#unit 4 기본문법


*   파이썬은 주석을 사용하지 않음
*   #을 통해 주석 사용가능
*   들여쓰기 하면 좋음

#unit 5 숫자계산


*   int 정수
*   float 실수
*   complex 복소수
"""

# 덧셈
1 + 1

# 뺄셈 
1 -  2

# 곱셈
2 * 2

# 나눗셈
5 / 2

# 몫 출력
5 // 2

# 나머지 출력
5  %  2

# 거듭제곱
2 ** 10

# 객체의 자료형 출력
type(10)

# 몫과 나머지 함께 구하기
divmod(4, 2)

# 복소수
1.2 + 1.3j

"""#unit 6 변수와 입출력"""

# 변수 만들기
x = 10
x

y = 'Hello world'
y

# 변수의 자료형 
type(x)

type(y)

# 변수 여러 개를 한 번에 만들기
x, y, z = 10, 20, 30
x

y

z

# 변수의 값이 같을 때
x = y = z = 10
x

y

z

# 변수 삭제
x = 10
del x
x

# 빈 변수 만들기
x = None
print(x)

# 산술 연산 후 할당 연산자 사용하기
a = 10
a = a + 20    # a와 20을 더한 후 결과를 다시 a에 저장 a += 20 과 같음
a

# input 함수
input()

# input 함수의 결과를 변수에 할당
x = input()

x

x = input('문자열을 입력하세요: ')
x

# 두 숫자의 합 구하기
a = input("첫 번째 숫자를 입력하세요: ")
b = input("두 번째 숫자를 입력하세요: ")

print(a + b)

# 입력 값을 정수로 변환하기
a = int(input("첫 번째 숫자를 입력하세요: "))
b = int(input("두 번째 숫자를 입력하세요: "))
print(a + b)

# 입력 값을 변수 두 개에 저장하기
a, b = input("문자열 두 개를 입력하세요: ").split()
print(a)
print(b)

2# 두 숫자의 합 구하기
a, b = input("숫자 두 개를 입력하세요: ").split()
print(a + b)

# 입력 값을 정수로 변환하기
a, b = input("숫자 두 개를 입력하세요: ").split()
a = int(a)
b = int(b)
print(a + b)

# map을 사용하여 정수로 변환하기
a, b = map(int, input("숫자 두 개를 입력하세요: ").split())
print(a + b)

# 입력받은 값을 콤마를 기준으로 분리하기
a, b = map(int, input("숫자 두 개를 입력하세요: ").split(","))
print(a + b)

# 연습문제
a, b, c = map(int, input("숫자 세 개를 입력하세요: ").split())
print(a + b + c)

"""#unit 7 출력"""

# 값을 여러 개 출력하기 - ,
print(1, 2, 3)

print('Hello', 'Python')

# sep로 값 사이에 문자 넣기
print(1, 2, 3, sep=',') # sep에 콤마와 공백을 지정

print(4, 5, 6, sep=',')    # sep에 콤마만 지정

print('Hello', 'Python', sep='')    # sep에 빈 문자열을 지정

print(1920, 1080, sep='x')    # sep에 x를 지정

# 줄바꿈
print(1, 2, 3, sep = '\n')

print('1\n2\n3')    # 문자열 안에 \n을 사용하여 줄바꿈

# end 사용하기
print(1, end=' ') 
print(2, end=' ')
print(3)

# 연습문제
year = 2000
month = 10
day = 27
hour = 11
minute = 43
second = 59

print(year, month, day, sep='/', end = ' ')
print(hour, minute, second, sep=':')